### ISSUE TITLE
Visual glitch after fresh install

### ISSUE THREAD

**Issue by fonorobert** [toggl/superday#808] opened 2017-10-12 10:55 UTC
After fresh install and going through the initial setup process, it looks like the last step of the setup is displayed at the same time as the empty state of the app:
![image uploaded from ios](https://user-images.githubusercontent.com/6963710/31492704-872c9e78-af4c-11e7-85de-b254f75264f1.png)

**Comment by pe0ny** [comment] 2017-10-19 06:08
@sofokli1 Can you check it out? For me it happens during app locates me.

**Comment by pe0ny** [comment] 2017-10-19 07:38
The issue is that the last step of the setup is displayed at the same time as the empty state. But it could be cause by not creating leisure slot, hence the empty state.

**Comment by sofokli1** [comment] 2017-10-19 17:52
tried with the smartguess branch and i can't reproduce

**Comment by sofokli1** [comment] 2017-10-20 10:04
the only reason that i see how this can happen is if we do not have the user location in time for the timeline generation algorithm. the lack of location would throw an error in the algo and thus the algo would not go on to the point where it crates the first timeslot of the day. will take a look and see how it can be fixed.

**Comment by sofokli1** [comment] 2017-10-20 13:42
@pe0ny can't reproduce on real device. i only see it simulator. Who ever has this issue most likely has a device prior to iphone 5s

**Comment by pe0ny** [comment] 2017-10-20 13:57
@sofokli1 then let's close it and investigate again when more users start complaining.

**Comment by amulware** [comment] 2017-10-24 13:26
This was reported to still be a problem on iPhone 6s with iOS 10

**Closed** 2017-12-12 10:17 UTC
Labels: pending-review
