### ISSUE TITLE
Crash due to memory issue

### ISSUE THREAD

**Issue by Odrakir** [toggl/superday#931] opened 2017-12-06 07:26 UTC
After editing time slots for some time the app crashes and XCode just says "terminating due to memory issue"

**Comment by sofokli1** [comment] 2017-12-06 18:19
The problem is in the whole app not just the details view. It is related to retain cycles due to the use of `self` in map operations on `Observables`. `Observables` keep a hold of `self` and are added to the `disposeBag`. The `disposeBag` has a reference to `self` and on the same time is waiting for self to dealloc in order to call `dispose` on the disposable.

I suggest the following solutions:
1. Quick and easy fix. Just add `[unowned self]` and move on with our life
2. A lot of work fix. Use `[weak self]` and the avalanche of `?` and `if let` that will have to be added

I personally tried solution `1` and it worked on the details view

P.S.: Most likely this issue is the reason for the timeline not being released as well (previously it was accredited to the pager/apple)

**Comment by Odrakir** [comment] 2017-12-06 18:45
Yeah, I know how retain cycles work in Swift. And I know most times they happen due to a reference to `self` from inside a closure that is somehow retained by the same `self`, as in RxSwift operators in a sequence whose disposables get added to a `disposeBag`. 

But the thing is you can't go adding `[unowned self]` (or even `[weak self]`) everywhere. You have to find where the leak is and fix that specific problem. So if you found a place where adding `[unowned self]` fixes a retain cycle, and also this crash, great. Make a PR.

**Comment by sofokli1** [comment] 2017-12-07 09:36
If we are using `self` as described above, I think it will always lead to retain cycle. On the other hand the good news is that we are not using `self` everywhere. I think is a good idea to use one of the fixes (or something else that also fixes this) as a default rule so that we prevent retain cycles from being created in the first place and not just fix them when we catch them.

I will make a PR for the details view

**Closed** 2017-12-13 17:58 UTC
Labels: bug, pending-review
