### ISSUE TITLE
Timeline doesn't display movement tags

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#1013] opened 2018-02-08 14:50 UTC
Timeline (both in collapsed and expanded states) doesn't display movement tags like walk, run etc though it should. 

Links to correct zeplin files: https://zpl.io/VkKkEK5 & https://zpl.io/bPrlvq6

**Comment by Odrakir** [comment] 2018-02-12 16:51
This happens because of the changes to models and DB. We need to persiste all the motion data as expected now and get the activity from TimeSlotEntity. As it will be able to have many different activities, we should probably get just the longest one.

**Comment by Odrakir** [comment] 2018-02-14 08:28
As we are already doing the motion migration in another PR. Let's use this opportunity to check this works and find a way to reproduce it again (probably by deleting the imported motion events)

**Comment by sofokli1** [comment] 2018-02-14 20:13
I see 2 options here:
- we either roll back to the old times when this was working with the timeSlotService in timeline
- we push for the migration (and use new tables in database for all the `...PM` models)

**Comment by sofokli1** [comment] 2018-02-14 20:14
First option makes sense only if we are releasing a soon

**Comment by Odrakir** [comment] 2018-02-15 07:51
@sofokli1 So, these are the classes that use `TimeSlotService` to get the timeslots (directly or indirectly through `getActivities`). In *bold* are the ones that we need to change.

TimeslotDetailViewModel (I'm removing it for this one, we don't need TS anymore)
DefaultCategoryProvider
*GoalViewModel*
Persister (only for logging, we can remove it for now)
TimelineProcessor
DefaultSmartGuessService
*WeeklySummaryViewModel* (getTimeSlots and getActivities)
*DefaultGoalService* (needs a get goals interactor)
*DailySummaryViewModel* (getActivities)
*PagerViewModel* (getActivities)
*CalendarViewModel* (getActivities)
*RatingViewModel* (getActivities)
MigrateOldMotionEvents (this one is ok)

As you can see 4 of those will be fixed with a getActivities interactor, then we need another interactor for goals and probably the rest can be fixed with the GetTimeSlotsForDate interactor that already exists.

So, I'd say we try to do these changes now, hopefully we can do them all by today or tomorrow.

**Comment by Odrakir** [comment] 2018-02-20 07:19
I'm going to close this issue, as this is really multiple issues.

**Closed by Odrakir** 2018-02-20 07:19 UTC
Labels: bug
