### ISSUE TITLE
Opening app from notification does not always open edit view

### ISSUE THREAD

**Issue by amulware** [toggl/superday#677] opened 2017-07-24 06:41 UTC
I believe it should, right? It also does not appear to scroll to the bottom of a longer timeline.

**Comment by sofokli1** [comment] 2017-07-28 09:59
can't reproduce. may have been fixed with issue #643 fix

**Comment by amulware** [comment] 2017-07-28 10:00
That seems very possible. Let's keep an eye on it!

**Comment by sofokli1** [comment] 2017-08-02 13:19
I am closing this since we are removing notifications

**Closed by sofokli1** 2017-08-02 13:19 UTC
Labels: on-hold
