### ISSUE TITLE
Check if smart-guess algorithm is working correctly

### ISSUE THREAD

**Issue by amulware** [toggl/superday#595] opened 2017-05-31 11:08 UTC
It appears that at least for some (most? all?) people no categories are guessed (except commute, but this is a special case).

We have to investigate and figure out what is going on with this. If there is a bug, fix it. If there is not, let's see if we can improve it somehow (without unreasonable effort) to work better again.

**Comment by Odrakir** [comment] 2017-06-20 13:18
I've added some more logging to the app, let's see where that gets us.

**Comment by Odrakir** [comment] 2017-07-04 11:14
After looking at this a lot, I don't think there's anything wrong with the code itself. The problem is in the logic we use to handle smart guesses. For the amount of guesses I usually have (around 20) it's not easy to find one 5 hours away within a week from a given new time slot.

This will be probably fixed with #657 or #651. So I would close this for now.

I'm thinking, maybe we should also include some default smart guesses. For example: For almost everybody (except Paul) breakfast is around 8:30.

**Closed** 2017-07-06 15:58 UTC
