### ISSUE TITLE
App creates new slot almost right after creating manual slot

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#821] opened 2017-10-20 10:09 UTC
> when i create a manual slot the app then starts a new slot after that usually.  eg. i sit down, open the app, create a manual entry for work and put down the phone. i'd then expect the app to keep tracking that entry but instead most often it creates a new blank empty right after that (i assume since it notices i stopped moving around) so whenever i create a manual entry it's a 0min entry followed immediately by an uncategorized one that's the actual time i spent there.

**Comment by amulware** [comment] 2017-10-20 10:18
This sounds like intended behaviour. I haven't heard anything about treating cases like this especially. How do you propose we address this?

**Comment by sofokli1** [comment] 2017-10-20 10:23
i have an idea. if the last timeslot before creating a timeline was `set by user` and the activity tag is the same, than use that category for the new slot (if not smartguessed already)

**Comment by amulware** [comment] 2017-10-20 10:29
Could work, but I think it should take time into consideration as well. Or maybe only use time? If it's been only 30 seconds since the start of the slot, there is no point in creating a new one. Not sure what a reasonable limit is though.

**Comment by sofokli1** [comment] 2017-10-20 10:33
a simpler approach would be to just discard the first timeslot that is created from the algo

**Comment by amulware** [comment] 2017-10-20 10:37
Under all circumstances?

**Comment by sofokli1** [comment] 2017-10-20 10:42
i see 2 paths.
1. you open the app and do nothing and close it.
2. you open the app and add a slot manually.
in both cases when you open the app later the first timeslot most likely is what the previews last slot was.

**Comment by pe0ny** [comment] 2017-10-20 10:57
> i have an idea. if the last timeslot before creating a timeline was set by user and the activity tag is the same, than use that category for the new slot (if not smartguessed already)

By activity tag you mean these 'still', 'walk' etc? If so I think it makes sense.

**Comment by Odrakir** [comment] 2017-11-07 10:50
I can't reproduce this with the current debug build. I moved around the house, then sat back and created a work TS, after 5 minutes it's still there... Does it still happen to you? Can you attach screenshots?

**Comment by Odrakir** [comment] 2017-11-07 10:58
Never mind, I've just seen it happen, it took a little longer than I expected. Let me think of a fix.

**Closed** 2017-11-08 11:17 UTC
Labels: pending-review
